#!/usr/bin/env bash
FILE=$1
FTP_URL="ftp://${FTP_USERNAME}:${FTP_PASSWORD}@${FTP_HOSTNAME}${FTP_PATH}${FILE}"
S3_URL="s3://${MOVIES_BUCKET}/incoming/${FILE}"

function file_exists() {
  curl ftp://${FTP_USERNAME}:${FTP_PASSWORD}@${FTP_HOSTNAME}${FTP_PATH} 2> /dev/null \
    | grep "${FILE}" &> /dev/null
  return $?
}

function log() {
  echo "$@"
}

function migrate_to_s3() {
  wget ${FTP_URL} -O - 2> /dev/null \
    | aws s3 cp --storage-class REDUCED_REDUNDANCY - ${S3_URL}
  return $?
}

function delete() {
  file=$1
  log "Deleting ${FILE} from FTP"
  lftp ftp://${FTP_USERNAME}:${FTP_PASSWORD}@${FTP_HOSTNAME}${FTP_PATH} \
     -e "rm ${FILE}; exit"
}

###############################################################################

if file_exists; then
  migrate_to_s3 || exit 1
  delete
fi

exit 0
