#!/usr/bin/env bash
shopt -s expand_aliases
alias ftp_path="echo ${FTP_PATH}/$1"
alias s3_path="echo incoming/$1"
alias usage="echo '$0 <file_on_ftp>' >&2"

function file_exists() {
  # file exists on the FTP server
}

function log() {
  # publish to cloudwatch logs
}

function download() {
  file=$1
  log "Downloading ${file} from FTP"
}

function upload() {
  file=$1
  log "Uploading ${file} to S3"
}

function delete() {
  file=$1
  log "Deleting ${file} from FTP"
}

###############################################################################

[[ $# -ne 1 ]] && usage && exit 1

file=$1
trap "{ rm -f /tmp/${file}; }" EXIT

if file_exists; then
  download ${file} || exit 1
  upload ${file} || exit 1
  delete ${file}
fi

exit 0
